package com.obe.quranid2.module.hisnulmuslim.model;

import com.obe.quranid2.R;

public class ItemHm {
    public static int[] imageDua = {
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next,
            R.drawable.ic_next
    };
    public static String[] shortNumber ={
      "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"
    };
    public static String[] title ={
      "Bacaan ketika bangun  dari tidur",
      "Do'a ketika mengenakan pakaian",
      "Do'a mengenakan pakaian baru",
      "Do'a untuk orang yang mengenakan pakaian baru",
      "Do'a ketika menanggalkan pakaian",
      "Do'a masuk WC",
      "Do'a keluar dari WC",
      "Bacaan sebelum wudhu",
      "Bacaan setelah wudhu",
      "Bacaan ketika keluar rumah",
      "Bacaan apabila masuk rumah",
      "Do'a Pergi ke masjid",
      "Do'a masuk masjid",
      "Do'a keluar masjid",
      "Bacaan ketika mendengar adzan",
      "Do'a istiftah",
      "Do'a ruku",
      "Do'a bangun dari ruku",
      "Do'a sujud",
      "Do'a duduk antara dua sujud",
      "Do'a sujud tilawah",
      "Tasyahud",
      "Membaca shalawat Nabi setelah tasyahud",
      "Do'a setelah tasyahud akhir sebelum salam",
      "Do'a shalat istikharah",
      "Dzikir menjelang tidur",
      "Do'a jika terbangun pada malam hari",
      "Do'a apabila ada yang menakutkan dalam tidur",
      "Apa yang dilakukan jika bermimpi buruk",
      "Do'a kunut witir",
      "Dzikir setelah slam shalat witir"
    };
    public static String[] category = {
            "Pagi dan Malam",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Sholat",
            "Sholat",
            "Rumah dan Keluarga",
            "Rumah dan Keluarga",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Sholat",
            "Menyembah Allah",
            "Pagi dan Malam",
            "Kebahagiaan dan Kesulitan",
            "Kebahagiaan dan Kesulitan",
            "Kebahagiaan dan Kesulitan",
            "Sholat",
            "Sholat"
    };
}
