package com.obe.quranid2.module.juzamma.model;

import com.obe.quranid2.R;

public class ItemJa {

    public static int[] imageSurah = {
            R.drawable.sname_1,
            R.drawable.sname_78,
            R.drawable.sname_79,
            R.drawable.sname_80,
            R.drawable.sname_81,
            R.drawable.sname_82,
            R.drawable.sname_83,
            R.drawable.sname_84,
            R.drawable.sname_85,
            R.drawable.sname_86,
            R.drawable.sname_87,
            R.drawable.sname_88,
            R.drawable.sname_89,
            R.drawable.sname_90,
            R.drawable.sname_91,
            R.drawable.sname_92,
            R.drawable.sname_93,
            R.drawable.sname_94,
            R.drawable.sname_95,
            R.drawable.sname_96,
            R.drawable.sname_97,
            R.drawable.sname_98,
            R.drawable.sname_99,
            R.drawable.sname_100,
            R.drawable.sname_101,
            R.drawable.sname_102,
            R.drawable.sname_103,
            R.drawable.sname_104,
            R.drawable.sname_105,
            R.drawable.sname_106,
            R.drawable.sname_107,
            R.drawable.sname_108,
            R.drawable.sname_109,
            R.drawable.sname_110,
            R.drawable.sname_111,
            R.drawable.sname_112,
            R.drawable.sname_113,
            R.drawable.sname_114,
    };

    public static String[] surahNumber = {
      "1", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114",
    };

    public static String[] surahText ={
            "Al-Fatihah",
            "An-Naba'",
            "An-Nazi'at'",
            "'Abasa",
            "At-Takwir",
            "Al-Infitar",
            "Al-Muthaffifiin",
            "Al-Insyiqaq",
            "Al-Buruj",
            "At-Tariq",
            "Al-A'la",
            "Al-Ghasyiyah",
            "Al-Fajr",
            "Al-Balad",
            "As-Syams",
            "Al-Lail",
            "Ad-Duha",
            "Al-Insyirah",
            "At-Tin",
            "Al-'Alaq",
            "Al-Qadr",
            "Al-Bayyinah",
            "Az-Zalzalah",
            "Al-'Adiyat",
            "Al-Qari'ah",
            "At-Takasur",
            "Al-'Asr",
            "Al-Humazah",
            "Al-Fil",
            "Quraisy",
            "Al-Ma'un",
            "Al-Kausar",
            "Al-Kafirun",
            "AN-Nasr",
            "Al-Lahab",
            "Al-Ikhlas",
            "Al-Falaq",
            "An-Nas"

    };

    public static String[] indoText = {
            "Pembukaan",
            "Berita Besar",
            "Malaikat-Malaikat yang Mencabut",
            "Ia Bermuka Masam",
            "Menggulung",
            "Terbelah",
            "Orang-orang yang Curang",
            "Terbelah",
            "Gugusan Bintang",
            "Yang Datang di Malam hari",
            "Yang Paling TInggi",
            "Hari Pembalasan",
            "Fajar",
            "Negeri",
            "Matahari",
            "Malam",
            "Waktu Duha",
            "Kelapangan",
            "Buah Tin",
            "Segumpal Darah",
            "Kemuliaan",
            "Bukti yang Nyata",
            "Keguncangan",
            "Kuda Perang yang Berlari Kencang",
            "Hari Kiamat",
            "Bermegah-Megahan",
            "Masa",
            "Pengumpat",
            "Gajah",
            "Suku Quraysy",
            "Barang-barang yang Berguna",
            "Nikmat yang Banyak",
            "Orang-orang Kafir",
            "Pertolongan",
            "Gejolak Api",
            "Kemurnian Keesaan Allah",
            "Waktu Subuh",
            "Manusia"
    };

    public static String[] type ={
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Madinah",
            "Madinah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
            "Mekah",
    };

    public static String[] totalAyah = {
            "7 Ayat",
            "40 Ayat",
            "46 Ayat",
            "42 Ayat",
            "29 Ayat",
            "19 Ayat",
            "36 Ayat",
            "25 Ayat",
            "22 Ayat",
            "17 Ayat",
            "19 Ayat",
            "26 Ayat",
            "30 Ayat",
            "20 Ayat",
            "15 Ayat",
            "21 Ayat",
            "11 Ayat",
            "8 Ayat",
            "8 Ayat",
            "19 Ayat",
            "5 Ayat",
            "8 Ayat",
            "8 Ayat",
            "11 Ayat",
            "11 Ayat",
            "8 Ayat",
            "3 Ayat",
            "9 Ayat",
            "5 Ayat",
            "4 Ayat",
            "7 Ayat",
            "3 Ayat",
            "6 Ayat",
            "3 Ayat",
            "5 Ayat",
            "4 Ayat",
            "5 Ayat",
            "6 Ayat"
    };

}
